services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
    volumes:
      - ./app:/app/app
      - ./frontend:/app/frontend
      - ./test.db:/app/test.db
      - ./models:/app/models
    networks:
      - github-monitor-network
    restart: unless-stopped

networks:
  github-monitor-network:
    driver: bridge